import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileDown,
  FileText,
  Filter,
  Github,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  BarChart,
  BarChart2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Home,
  type LucideIcon,
  MapPin,
  BarChart4,
  Layers,
  Tag,
  PieChart,
  ChevronDown,
  ChevronUp,
  RefreshCw,
  ShoppingCart,
  Download,
  LogOut,
  Map,
  Palette,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  pizza: Pizza,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  twitter: Twitter,
  check: Check,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  fileText: FileText,
  download: Download,
  fileDown: FileDown,
  map: Map,
  mapPin: MapPin,
  chart: BarChart,
  chartAlt: BarChart2,
  chartComplex: BarChart4,
  layers: Layers,
  tag: Tag,
  pieChart: PieChart,
  refresh: RefreshCw,
  cart: ShoppingCart,
  home: Home,
  github: Github,
  logout: LogOut,
  palette: Palette,
  filter: Filter,
}
